name: 'Stale and Close PR'
on:
  schedule:
    - cron: '*/6 * * * *'
    
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
         
         
          # comment on PR if not active for more then 14 days.
          stale-pr-message: 'This PR has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Thank you.'
        
          #comment on PR if stale for more then 14 days. 
          close-pr-message: "Closing as stale. Please reopen if you'd like to work on this further"
        
       
          # Number of days of inactivity before a stale PR is closed
          days-before-pr-close: 0
       
          # Number of days of inactivity before an PR Request becomes stale
          days-before-pr-stale: 0
         
          #Check for label to stale or close the issue/PR
          any-of-labels: 'awaiting response'
         
          #override stale to stalled for PR
          stale-pr-label: 'Stalled'

